/**
 * ZeyTech AI Commerce OS — Robust Catalog Seeder for 25 Extended Flagship Products
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const products = [
  {
    id: 1,
    category: 1,
    subCategory: 1,
    productName: 'Apple MacBook Pro 16" M3 Max',
    productCompany: 'Apple',
    productPrice: 3499,
    productPriceBeforeDiscount: 3999,
    productDescription: 'Apple M3 Max chip with 16-core CPU, 40-core GPU, 48GB Unified Memory, 1TB SSD Storage. 16.2-inch Liquid Retina XDR display with ProMotion 120Hz.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      chip: "Apple M3 Max",
      cpu: "16-Core",
      gpu: "40-Core",
      ram: "48GB Unified",
      storage: "1TB NVMe SSD",
      display: "16.2 Liquid Retina XDR 120Hz",
      ports: ["3x Thunderbolt 4", "HDMI", "SDXC", "MagSafe 3"],
      weight: "2.16 kg",
      color: "Space Black"
    }),
    productModel: 'MBP16-M3MAX-48-1TB',
    ficheTechnique: "Fiche Technique Officielle:\n- Processeur : Puce Apple M3 Max (16 cœurs CPU / 40 cœurs GPU)\n- Mémoire Unifiée : 48 Go\n- Stockage : 1 To SSD ultra-rapide\n- Écran : Liquid Retina XDR 16,2 pouces avec ProMotion 120 Hz\n- Autonomie : Jusqu'à 22 heures\n- Garantie : 1 an constructeur Apple Maroc\n- توصيل سريع لجميع المدن المغربية مع إمكانية الدفع عند الاستلام.",
    stockQuantity: 100,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 2800,
    viewsCount: 1420,
    stockAvailable: 58,
    stockReserved: 1,
    stockSold: 41,
    name: 'Apple MacBook Pro 16" M3 Max',
    description: 'Apple M3 Max chip with 16-core CPU, 40-core GPU, 48GB Unified Memory, 1TB SSD Storage.',
    price: 3499.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      processor: "Apple M3 Max 16-Core",
      memory: "48GB Unified Memory",
      storage: "1TB SSD",
      display: "16.2 Liquid Retina XDR 120Hz",
      warranty: "1 Year Apple Direct Maroc"
    })
  },
  {
    id: 2,
    category: 1,
    subCategory: 2,
    productName: 'Dell XPS 15 9530 OLED Touch',
    productCompany: 'Dell',
    productPrice: 2299,
    productPriceBeforeDiscount: 2599,
    productDescription: 'Intel Core i9-13900H 14-Core, NVIDIA GeForce RTX 4070 8GB GDDR6, 32GB DDR5 RAM, 1TB PCIe NVMe SSD, 15.6" 3.5K (3456x2160) OLED InfinityEdge Touch Display.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      processor: "Intel Core i9-13900H",
      graphics: "NVIDIA RTX 4070 8GB",
      ram: "32GB DDR5 4800MHz",
      storage: "1TB M.2 PCIe NVMe",
      display: "15.6 3.5K OLED Touch",
      chassis: "CNC Machined Aluminum with Carbon Fiber Palmrest",
      weight: "1.92 kg"
    }),
    productModel: 'XPS-15-9530-OLED',
    ficheTechnique: "Fiche Technique:\n- Processeur : Intel Core i9-13900H\n- Carte Graphique : NVIDIA GeForce RTX 4070 8GB\n- RAM : 32 Go DDR5\n- Stockage : 1 To SSD\n- Écran : 15.6 3.5K OLED Tactile\n- Garantie : 1 an Dell Maroc",
    stockQuantity: 60,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 1850,
    viewsCount: 890,
    stockAvailable: 45,
    stockReserved: 0,
    stockSold: 15,
    name: 'Dell XPS 15 9530 OLED Touch',
    description: 'Intel Core i9-13900H, RTX 4070, 32GB RAM, 1TB SSD, 3.5K OLED Touch.',
    price: 2299.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      processor: "Intel Core i9-13900H",
      gpu: "NVIDIA RTX 4070 8GB",
      ram: "32GB DDR5",
      storage: "1TB SSD",
      display: "15.6 3.5K OLED Touch"
    })
  },
  {
    id: 3,
    category: 2,
    subCategory: 3,
    productName: 'Apple iPhone 16 Pro Max 512GB',
    productCompany: 'Apple',
    productPrice: 1599,
    productPriceBeforeDiscount: 1749,
    productDescription: 'A18 Pro Bionic Chip, Grade 5 Titanium design with textured matte glass back, 6.9-inch Super Retina XDR display with ProMotion and Always-On, 48MP Fusion camera system with 5x optical zoom.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      chip: "Apple A18 Pro",
      display: "6.9 Super Retina XDR OLED 120Hz ProMotion",
      storage: "512GB NVMe",
      camera: "48MP Main + 48MP Ultra Wide + 12MP 5x Telephoto",
      material: "Grade 5 Titanium",
      battery: "Up to 33 hours video playback",
      color: "Natural Titanium"
    }),
    productModel: 'IPH16PM-512-NAT',
    ficheTechnique: "Fiche Technique:\n- Puce : Apple A18 Pro avec Neural Engine 16 cœurs\n- Stockage : 512 Go\n- Écran : 6,9 pouces Super Retina XDR OLED ProMotion\n- Caméra : Triple capteur 48 MP avec zoom optique 5x\n- Châssis : Titane Grade 5 ultra-résistant\n- هاتف أصلي 100% مع ضمان معتمد في المغرب.",
    stockQuantity: 85,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 1250,
    viewsCount: 3200,
    stockAvailable: 68,
    stockReserved: 0,
    stockSold: 17,
    name: 'Apple iPhone 16 Pro Max 512GB',
    description: 'A18 Pro Bionic Chip, Grade 5 Titanium design, 6.9-inch display, 48MP camera.',
    price: 1599.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      chip: "Apple A18 Pro",
      storage: "512GB",
      display: "6.9 Super Retina XDR OLED 120Hz",
      camera: "48MP Triple Pro System"
    })
  },
  {
    id: 4,
    category: 2,
    subCategory: 4,
    productName: 'Samsung Galaxy S25 Ultra 512GB',
    productCompany: 'Samsung',
    productPrice: 1499,
    productPriceBeforeDiscount: 1649,
    productDescription: 'Snapdragon 8 Gen 4 for Galaxy, 6.8-inch Dynamic AMOLED 2X 120Hz Anti-Reflective Display, 200MP Quad Telephoto Camera, Built-in S Pen, Titanium Armor Frame.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      processor: "Snapdragon 8 Gen 4 for Galaxy",
      ram: "16GB LPDDR5X",
      storage: "512GB UFS 4.0",
      display: "6.8 Dynamic AMOLED 2X 1-120Hz Gorilla Armor",
      camera: "200MP + 50MP + 50MP + 12MP",
      spen: "Embedded Bluetooth S Pen",
      battery: "5000mAh with 45W Fast Charging"
    }),
    productModel: 'SM-S938B-512',
    ficheTechnique: "Fiche Technique:\n- Processeur : Qualcomm Snapdragon 8 Gen 4 for Galaxy\n- RAM : 16 Go / Stockage : 512 Go\n- Écran : 6,8 Dynamic AMOLED 2X avec verre Gorilla Armor antireflet\n- Appareil Photo : 200 MP avec Galaxy AI\n- Stylet S Pen intégré\n- متوفر للتوصيل الفوري مع كفالة سامسونج المغرب.",
    stockQuantity: 75,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 1150,
    viewsCount: 2100,
    stockAvailable: 52,
    stockReserved: 0,
    stockSold: 23,
    name: 'Samsung Galaxy S25 Ultra 512GB',
    description: 'Snapdragon 8 Gen 4, 6.8-inch AMOLED 2X, 200MP Camera, S Pen.',
    price: 1499.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      processor: "Snapdragon 8 Gen 4",
      ram: "16GB",
      storage: "512GB",
      camera: "200MP Quad AI Camera",
      spen: true
    })
  },
  {
    id: 5,
    category: 3,
    subCategory: 5,
    productName: 'Sony WH-1000XM5 Wireless Noise Canceling',
    productCompany: 'Sony',
    productPrice: 399,
    productPriceBeforeDiscount: 449,
    productDescription: 'Industry-leading noise canceling with two processors and 8 microphones, Auto NC Optimizer, Magnificent sound quality with 30mm carbon fiber driver unit, 30-hour battery life.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      driver: "30mm Carbon Fiber Composite",
      anc: "Integrated Processor V1 + HD Noise Canceling Processor QN1 (8 Microphones)",
      codecs: ["LDAC", "AAC", "SBC"],
      battery: "30 Hours (ANC On) / 40 Hours (ANC Off)",
      multipoint: "2 Devices Simultaneous",
      weight: "250g"
    }),
    productModel: 'WH1000XM5-BLK',
    ficheTechnique: "Fiche Technique:\n- Réduction de Bruit : Double processeur HD QN1 + V1 avec 8 micros\n- Autonomie : 30 heures avec réduction de bruit activée\n- Audio Haute Résolution : Compatible LDAC et Hi-Res Wireless\n- Confort : Cuir souple Soft Fit ultra-léger\n- Casque audio haute fidélité avec livraison gratuite au Maroc.",
    stockQuantity: 120,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 270,
    viewsCount: 1850,
    stockAvailable: 95,
    stockReserved: 0,
    stockSold: 25,
    name: 'Sony WH-1000XM5 Wireless Noise Canceling',
    description: 'Industry-leading noise canceling headphones with 30-hour battery life.',
    price: 399.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      driver: "30mm Carbon Fiber",
      anc: "Dual QN1 + V1 Engine",
      battery: "30 Hours",
      codecs: "LDAC / AAC"
    })
  },
  {
    id: 6,
    category: 3,
    subCategory: 5,
    productName: 'Apple AirPods Max Space Gray',
    productCompany: 'Apple',
    productPrice: 549,
    productPriceBeforeDiscount: 599,
    productDescription: 'Apple-designed dynamic driver provides high-fidelity audio. Active Noise Cancellation with Transparency mode. Spatial audio with dynamic head tracking for theater-like sound.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      driver: "40mm Apple Custom Dynamic",
      chip: "Apple H1 Headphone Chip (each ear cup)",
      anc: "Active Noise Cancellation + Transparency Mode",
      audio: "Personalized Spatial Audio with dynamic head tracking",
      materials: "Anodized Aluminum Cups, Stainless Steel Frame, Breathable Knit Mesh Canopy"
    }),
    productModel: 'AIRPODS-MAX-SG',
    ficheTechnique: "Fiche Technique:\n- Transducteur dynamique conçu par Apple pour un son haute fidélité\n- Réduction active du bruit et mode Transparence\n- Audio spatial personnalisé avec suivi dynamique des mouvements de la tête\n- Coussinets en maille respirante et arceau en acier inoxydable\n- Autonomie : 20 heures d'écoute.",
    stockQuantity: 50,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 420,
    viewsCount: 1100,
    stockAvailable: 38,
    stockReserved: 0,
    stockSold: 12,
    name: 'Apple AirPods Max Space Gray',
    description: 'High-fidelity audio with Active Noise Cancellation and Spatial Audio.',
    price: 549.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      driver: "40mm Dynamic Driver",
      anc: true,
      spatial_audio: true,
      battery: "20 Hours"
    })
  },
  {
    id: 7,
    category: 4,
    subCategory: 7,
    productName: 'Apple Watch Ultra 2 GPS + Cellular 49mm',
    productCompany: 'Apple',
    productPrice: 799,
    productPriceBeforeDiscount: 899,
    productDescription: 'Rugged 49mm titanium case with sapphire front crystal. Precision dual-frequency GPS. 3000 nits Always-On Retina display. Up to 36 hours of battery life with normal use.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      case: "49mm Aerospace-Grade Titanium",
      display: "Always-On Retina OLED up to 3000 nits",
      chip: "S9 SiP with 64-bit dual-core processor",
      water_resistance: "100m water resistant / EN13319 dive certified (40m)",
      sensors: ["ECG", "Blood Oxygen", "Depth Gauge", "Water Temperature"],
      connectivity: ["LTE", "Wi-Fi 4", "Bluetooth 5.3", "Dual-Frequency GPS"]
    }),
    productModel: 'AW-ULTRA2-49-TIT',
    ficheTechnique: "Fiche Technique:\n- Boîtier : 49 mm en titane aérospatial\n- Écran : Retina OLED toujours activé avec luminosité crête de 3 000 nits\n- Puce : S9 SiP avec geste Toucher deux fois (Double Tap)\n- Étanchéité : Jusqu'à 100 m et certifiée plongée récréative 40 m\n- Autonomie : Jusqu'à 72 heures en mode économie.",
    stockQuantity: 40,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 610,
    viewsCount: 950,
    stockAvailable: 28,
    stockReserved: 0,
    stockSold: 12,
    name: 'Apple Watch Ultra 2 GPS + Cellular 49mm',
    description: 'Rugged 49mm titanium smartwatch with dual-frequency GPS and 3000 nits display.',
    price: 799.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      case: "49mm Titanium",
      display: "3000 nits Retina OLED",
      water_resistance: "100m / Dive 40m",
      gps: "Dual-Frequency Precision"
    })
  },
  {
    id: 8,
    category: 5,
    subCategory: 8,
    productName: 'Sony PlayStation 5 Pro 2TB',
    productCompany: 'Sony',
    productPrice: 799,
    productPriceBeforeDiscount: 899,
    productDescription: 'PlayStation Spectral Super Resolution (PSSR) AI-driven upscaling, Advanced Ray Tracing, 2TB high-speed PCIe 4.0 NVMe SSD, 4K 120Hz & 8K HDR support, DualSense Wireless Controller included.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      gpu: "Upgraded RDNA Architecture with 67% more Compute Units",
      storage: "2TB Ultra-High Speed NVMe SSD",
      upscaling: "PlayStation Spectral Super Resolution (PSSR AI)",
      raytracing: "Advanced Ray Tracing Engine (2x-3x speed)",
      video_out: "HDMI 2.1 (Supports 4K 120Hz, 8K HDR, VRR)",
      controller: "DualSense with Haptic Feedback & Adaptive Triggers"
    }),
    productModel: 'PS5-PRO-2TB-ED',
    ficheTechnique: "Fiche Technique:\n- Processeur Graphique : GPU boosté avec architecture RDNA avancée (+67% CU)\n- Stockage : 2 To SSD NVMe ultra-rapide\n- Technologie IA : PlayStation Spectral Super Resolution (PSSR)\n- Ray Tracing avancé pour des reflets photoréalistes\n- Manette sans fil DualSense avec retours haptiques incluse\n- جهاز الألعاب الأقوى في العالم متوفر الآن في المغرب مع ضمان رسمي.",
    stockQuantity: 60,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 620,
    viewsCount: 4500,
    stockAvailable: 42,
    stockReserved: 0,
    stockSold: 18,
    name: 'Sony PlayStation 5 Pro 2TB',
    description: 'Next-gen console with PSSR AI upscaling, 2TB SSD, and Advanced Ray Tracing.',
    price: 799.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      storage: "2TB NVMe SSD",
      upscaling: "PSSR AI",
      raytracing: "Advanced 3x RT",
      controller: "DualSense Haptic"
    })
  },
  {
    id: 9,
    category: 6,
    subCategory: 9,
    productName: 'Dell UltraSharp 34" Curved USB-C Hub Monitor',
    productCompany: 'Dell',
    productPrice: 949,
    productPriceBeforeDiscount: 1099,
    productDescription: 'WQHD 3440 x 1440 at 60Hz curved IPS Black display with 2000:1 contrast ratio. Built-in 90W USB-C Power Delivery, RJ45 Ethernet, and KVM switch for multi-system productivity.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      panel: "34.14 Curved IPS Black (1900R)",
      resolution: "WQHD 3440 x 1440 at 60 Hz",
      contrast: "2000:1 True Contrast Ratio",
      color_gamut: "100% sRGB, 98% DCI-P3",
      connectivity: ["USB-C 90W PD", "RJ45 Ethernet (2.5Gbps)", "DisplayPort 1.4", "2x HDMI 2.1", "5x USB-A 10Gbps"],
      kvm: "Integrated Auto KVM Switch with PbP/PiP"
    }),
    productModel: 'U3423WE-CURVED',
    ficheTechnique: "Fiche Technique:\n- Dalle : 34,14\" Incurvée IPS Black (1900R)\n- Résolution : WQHD 3440 x 1440 avec ratio de contraste 2000:1\n- Connectivité Hub : USB-C 90W avec port Ethernet RJ45 2.5 Gbps\n- Fonctionnalités : Switch KVM automatique intégré pour contrôler 2 PC\n- Écran idéal pour les ingénieurs, designers et traders à Casablanca.",
    stockQuantity: 35,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 720,
    viewsCount: 680,
    stockAvailable: 24,
    stockReserved: 0,
    stockSold: 11,
    name: 'Dell UltraSharp 34" Curved USB-C Hub Monitor',
    description: '34-inch WQHD Curved IPS Black monitor with 90W USB-C Hub and KVM switch.',
    price: 949.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      panel: "34.14 Curved IPS Black",
      resolution: "WQHD 3440x1440",
      power_delivery: "90W USB-C",
      kvm: true
    })
  },
  {
    id: 10,
    category: 6,
    subCategory: 10,
    productName: 'Herman Miller Aeron Ergonomic Chair',
    productCompany: 'Herman Miller',
    productPrice: 1395,
    productPriceBeforeDiscount: 1595,
    productDescription: 'The benchmark for ergonomic seating. 8Z Pellicle breathable suspension membrane, PostureFit SL adjustable dual-pad lumbar support, Fully adjustable arms, Forward tilt limiter.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      material: "8Z Pellicle Elastomeric Suspension (Mineral/Graphite)",
      lumbar: "PostureFit SL Adjustable Sacral and Lumbar Pads",
      adjustments: ["Pneumatic Height", "Tilt Limiter with Forward Angle", "3D Adjustable Armrests", "Tension Control"],
      caster: "Hard Floor & Carpet Multi-Surface Wheels",
      warranty: "12-Year Herman Miller Manufacturer Warranty"
    }),
    productModel: 'AERON-SIZE-B-MIN',
    ficheTechnique: "Fiche Technique:\n- Suspension : Membrane 8Z Pellicle respirante brevetée\n- Soutien Lombaire : PostureFit SL réglable pour un alignement optimal de la colonne vertébrale\n- Accoudoirs : Réglables en hauteur, profondeur et angle pivotant\n- Garantie Constructeur : 12 ans certifiée Herman Miller\n- كرسي طبي مريح ومثالي للعمل المكتبي الطويل ومبرمجي الحاسوب.",
    stockQuantity: 25,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 950,
    viewsCount: 840,
    stockAvailable: 18,
    stockReserved: 0,
    stockSold: 7,
    name: 'Herman Miller Aeron Ergonomic Chair',
    description: 'Ergonomic office chair with 8Z Pellicle suspension and PostureFit SL lumbar.',
    price: 1395.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      mesh: "8Z Pellicle Suspension",
      lumbar: "PostureFit SL",
      warranty: "12 Years"
    })
  },
  {
    id: 11,
    category: 1,
    subCategory: 11,
    productName: 'Asus ROG Zephyrus G16 (2026) OLED Gaming Laptop',
    productCompany: 'Asus',
    productPrice: 2899,
    productPriceBeforeDiscount: 3299,
    productDescription: 'Intel Core Ultra 9 185H processor, NVIDIA GeForce RTX 4090 16GB GDDR6 Laptop GPU, 32GB LPDDR5X RAM, 2TB PCIe 4.0 NVMe SSD, 16.0" 2.5K 240Hz 0.2ms ROG Nebula OLED Display, CNC Aluminum Chassis.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      cpu: "Intel Core Ultra 9 185H",
      gpu: "NVIDIA RTX 4090 16GB (115W)",
      ram: "32GB LPDDR5X 7467MHz",
      storage: "2TB M.2 NVMe PCIe 4.0",
      display: "16.0 2.5K 240Hz 0.2ms ROG Nebula OLED DisplayHDR True Black 500",
      chassis: "Precision CNC Milled Aluminum with Slash Lighting",
      weight: "1.85 kg",
      battery: "90Wh with 100W USB-C PD"
    }),
    productModel: 'ROG-GU605MY-OLED',
    ficheTechnique: "Fiche Technique:\n- Processeur : Intel Core Ultra 9 185H avec NPU Intel AI Boost\n- Carte Graphique : NVIDIA GeForce RTX 4090 16 Go GDDR6\n- Mémoire : 32 Go LPDDR5X 7467 MHz\n- Écran : 16 2.5K 240 Hz OLED ROG Nebula avec temps de réponse 0.2 ms\n- Châssis : Aluminium CNC Platinum White avec barre d'éclairage Slash Lighting\n- Garantie : 2 ans Asus Maroc.",
    stockQuantity: 45,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 2300,
    viewsCount: 1650,
    stockAvailable: 38,
    stockReserved: 0,
    stockSold: 7,
    name: 'Asus ROG Zephyrus G16 (2026) OLED Gaming Laptop',
    description: 'Intel Core Ultra 9, RTX 4090, 32GB RAM, 2TB SSD, 16-inch 240Hz OLED display.',
    price: 2899.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      cpu: "Intel Core Ultra 9 185H",
      gpu: "RTX 4090 16GB",
      display: "16 240Hz OLED",
      ram: "32GB LPDDR5X",
      storage: "2TB NVMe"
    })
  },
  {
    id: 12,
    category: 2,
    subCategory: 12,
    productName: 'Apple iPad Pro 13" M4 Ultra-Thin OLED (1TB, Cellular)',
    productCompany: 'Apple',
    productPrice: 1899,
    productPriceBeforeDiscount: 2099,
    productDescription: 'Apple M4 chip, Tandem OLED Ultra Retina XDR Display with 1000 nits full-screen brightness, 1TB Storage, 16GB Unified Memory, Wi-Fi 7 + 5G Cellular, Incredibly thin 5.1mm design, Space Black.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      chip: "Apple M4 10-core CPU / 10-core GPU",
      display: "13.0 Tandem OLED Ultra Retina XDR 120Hz ProMotion (1600 nits peak)",
      storage: "1TB Flash NVMe",
      ram: "16GB Unified Memory",
      camera: "12MP Wide 4K ProRes + LiDAR Scanner",
      thickness: "5.1 mm (Thinnest Apple product ever)",
      connectivity: ["5G Sub-6GHz", "Wi-Fi 7", "Thunderbolt / USB 4"],
      weight: "582g"
    }),
    productModel: 'IPADPRO13-M4-1TB-5G',
    ficheTechnique: "Fiche Technique:\n- Processeur : Puce Apple M4 avec moteur neuronal 38 TOPS\n- Écran : Ultra Retina XDR 13 pouces avec technologie révolutionnaire Tandem OLED\n- Épaisseur : Seulement 5,1 mm (le produit Apple le plus fin de l'histoire)\n- Connectivité : 5G Cellular + Wi-Fi 7 ultra-rapide\n- Compatible avec Apple Pencil Pro et Magic Keyboard.",
    stockQuantity: 50,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 1520,
    viewsCount: 2100,
    stockAvailable: 42,
    stockReserved: 0,
    stockSold: 8,
    name: 'Apple iPad Pro 13" M4 Ultra-Thin OLED (1TB, Cellular)',
    description: 'Apple M4 chip, 13-inch Tandem OLED display, 1TB SSD, 16GB RAM, 5G Cellular.',
    price: 1899.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      chip: "Apple M4",
      display: "13.0 Tandem OLED XDR",
      thickness: "5.1mm",
      storage: "1TB",
      cellular: "5G LTE"
    })
  },
  {
    id: 13,
    category: 2,
    subCategory: 12,
    productName: 'Samsung Galaxy Tab S10 Ultra 5G (512GB, Moonstone Gray)',
    productCompany: 'Samsung',
    productPrice: 1399,
    productPriceBeforeDiscount: 1549,
    productDescription: '14.6" Dynamic AMOLED 2X 120Hz Anti-Reflection Display, MediaTek Dimensity 9300+ 4nm Processor, 16GB RAM, 512GB Storage with MicroSD expandability up to 1.5TB, S Pen included, IP68 Armor Aluminum.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      processor: "MediaTek Dimensity 9300+ (4nm)",
      display: "14.6 Dynamic AMOLED 2X 120Hz (2960 x 1848) Anti-Glare",
      ram: "16GB",
      storage: "512GB (expandable via MicroSD up to 1.5TB)",
      durability: "IP68 Water and Dust Resistance + Armor Aluminum Frame",
      battery: "11200mAh with 45W Super Fast Charging",
      spen: "Low-latency S Pen included in the box"
    }),
    productModel: 'SM-X926B-512-GRY',
    ficheTechnique: "Fiche Technique:\n- Processeur : MediaTek Dimensity 9300+ Octa-Core ultra-puissant\n- Écran géant : 14,6 pouces Dynamic AMOLED 2X avec traitement antireflet de pointe\n- Mémoire : 16 Go RAM / 512 Go de stockage extensible\n- Étanchéité : Certification IP68 pour la tablette et le stylet S Pen inclus\n- Mode Samsung DeX sans fil pour transformer la tablette en véritable PC de bureau.",
    stockQuantity: 40,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 1080,
    viewsCount: 1340,
    stockAvailable: 31,
    stockReserved: 0,
    stockSold: 9,
    name: 'Samsung Galaxy Tab S10 Ultra 5G (512GB, Moonstone Gray)',
    description: '14.6-inch Dynamic AMOLED 2X tablet with MediaTek Dimensity 9300+ and S Pen.',
    price: 1399.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      display: "14.6 Dynamic AMOLED 2X",
      processor: "Dimensity 9300+",
      storage: "512GB",
      spen: "Included",
      ip_rating: "IP68"
    })
  },
  {
    id: 14,
    category: 6,
    subCategory: 15,
    productName: 'Sony Alpha A7 IV Full-Frame Mirrorless Camera + 24-70mm GM II',
    productCompany: 'Sony',
    productPrice: 3199,
    productPriceBeforeDiscount: 3499,
    productDescription: '33MP Full-Frame Exmor R CMOS back-illuminated sensor, BIONZ XR image processor, 4K 60p 10-Bit 4:2:2 video, S-Cinetone color profile, 759-point Fast Hybrid AF with Real-time Eye AF, FE 24-70mm F2.8 GM II Lens.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      sensor: "33.0 MP Full-Frame Exmor R BSI CMOS",
      processor: "BIONZ XR Dual Engine",
      video: ["4K 60p (Super 35)", "4K 30p 7K oversampled 10-Bit 4:2:2", "S-Cinetone", "S-Log3"],
      autofocus: "759-Point Phase Detection with Real-time AI Eye AF for Human/Animal/Bird",
      stabilization: "5-Axis In-Body Image Stabilization (5.5 stops)",
      lens: "Sony FE 24-70mm F2.8 GM II Pro Zoom"
    }),
    productModel: 'ILCE-7M4-KIT-GM2',
    ficheTechnique: "Fiche Technique:\n- Capteur : 33 MP Plein Format Exmor R rétroéclairé\n- Processeur : BIONZ XR haute performance pour une vitesse de traitement 8x supérieure\n- Vidéo Cinéma : 4K 60p 10 bits 4:2:2 avec profils S-Cinetone et S-Log3\n- Objectif inclus : Sony FE 24-70mm f/2.8 G Master II (le zoom pro le plus compact et piqué au monde)\n- Garantie officielle Sony Maroc 2 ans.",
    stockQuantity: 30,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 2550,
    viewsCount: 1980,
    stockAvailable: 22,
    stockReserved: 0,
    stockSold: 8,
    name: 'Sony Alpha A7 IV Full-Frame Mirrorless Camera + 24-70mm GM II',
    description: '33MP Full-Frame mirrorless camera with 4K 60p 10-bit video and 24-70mm GM II lens.',
    price: 3199.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      sensor: "33MP Full-Frame Exmor R",
      video: "4K 60p 10-Bit 4:2:2",
      lens: "24-70mm F2.8 GM II",
      stabilization: "5-Axis IBIS"
    })
  },
  {
    id: 15,
    category: 6,
    subCategory: 15,
    productName: 'DJI Mavic 3 Pro Cine Drone (Triple Camera 4K/60fps ProRes)',
    productCompany: 'DJI',
    productPrice: 3899,
    productPriceBeforeDiscount: 4299,
    productDescription: 'Flagship triple-camera system featuring 4/3 CMOS Hasselblad 20MP Camera + 70mm Medium Tele + 166mm Telephoto, Apple ProRes 422 HQ recording on all three cameras, Built-in 1TB SSD, 43 min flight time, 15km transmission.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      cameras: ["Hasselblad 4/3 CMOS 20MP (24mm equiv)", "Medium Tele 1/1.3 CMOS 48MP (70mm equiv)", "Telephoto 1/2 CMOS 12MP (166mm equiv)"],
      codecs: ["Apple ProRes 422 HQ", "Apple ProRes 422", "Apple ProRes 422 LT", "H.264/H.265"],
      storage: "Built-in 1TB High-Speed SSD + MicroSD slot",
      flight_time: "Up to 43 minutes",
      transmission: "DJI O3+ HD Video up to 15 km",
      obstacle_sensing: "Omnidirectional APAS 5.0"
    }),
    productModel: 'MAVIC3-PRO-CINE',
    ficheTechnique: "Fiche Technique:\n- Système Tri-Caméra : Caméra principale Hasselblad 4/3 + Téléobjectif moyen 70 mm + Téléobjectif 166 mm\n- Enregistrement Vidéo : Apple ProRes 422 HQ sur les trois caméras avec SSD 1 To intégré\n- Autonomie de Vol : Jusqu'à 43 minutes par batterie\n- Détection d'Obstacles : Omnidirectionnelle APAS 5.0 pour une sécurité maximale\n- Outil ultime pour les tournages cinématographiques et documentaires au Maroc.",
    stockQuantity: 25,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 3100,
    viewsCount: 2400,
    stockAvailable: 19,
    stockReserved: 0,
    stockSold: 6,
    name: 'DJI Mavic 3 Pro Cine Drone (Triple Camera 4K/60fps ProRes)',
    description: 'Triple-camera cinema drone with Apple ProRes 422 HQ and built-in 1TB SSD.',
    price: 3899.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      cameras: "Triple: Hasselblad 4/3 + 70mm + 166mm",
      codecs: "Apple ProRes 422 HQ",
      storage: "1TB SSD",
      flight_time: "43 Mins"
    })
  },
  {
    id: 16,
    category: 3,
    subCategory: 5,
    productName: 'Bose QuietComfort Ultra Wireless Noise Cancelling Headphones',
    productCompany: 'Bose',
    productPrice: 429,
    productPriceBeforeDiscount: 479,
    productDescription: 'World-class active noise cancelling with CustomTune sound calibration technology, Breakthrough Bose Immersive Audio spatial sound, Ultra-plush synthetic leather cushions, Up to 24-hour battery life.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      spatial_audio: "Bose Immersive Audio Spatializer",
      anc: "CustomTune Active Noise Cancelling with Quiet, Aware, and Immersion Modes",
      battery: "Up to 24 hours (up to 18 hours with Immersive Audio)",
      connectivity: "Bluetooth 5.3 with Snapdragon Sound and aptX Adaptive",
      microphones: "10-Microphone array for crystal clear voice isolation"
    }),
    productModel: 'QC-ULTRA-BLK',
    ficheTechnique: "Fiche Technique:\n- Audio Spatial Immersif : Technologie Bose Immersive Audio qui spatialise le son en face de vous\n- Réduction de Bruit : Technologie CustomTune qui calibre le son à la morphologie de vos oreilles\n- Autonomie : Jusqu'à 24 heures d'écoute en continu (charge rapide 15 min pour 2h30)\n- Confort : Coussins ultra-doux en cuir synthétique haut de gamme\n- Livraison express 24h avec garantie Bose Maroc.",
    stockQuantity: 70,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 295,
    viewsCount: 1420,
    stockAvailable: 56,
    stockReserved: 0,
    stockSold: 14,
    name: 'Bose QuietComfort Ultra Wireless Noise Cancelling Headphones',
    description: 'World-class noise cancelling headphones with Bose Immersive Audio spatial sound.',
    price: 429.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      anc: "CustomTune ANC",
      audio: "Bose Immersive Spatial",
      battery: "24 Hours",
      bluetooth: "5.3 aptX Adaptive"
    })
  },
  {
    id: 17,
    category: 3,
    subCategory: 13,
    productName: 'Marshall Stanmore III Bluetooth Home Speaker (Brass & Black)',
    productCompany: 'Marshall',
    productPrice: 379,
    productPriceBeforeDiscount: 429,
    productDescription: '80W Total Output Power with wider stereo soundstage, Dynamic Loudness DSP, Bluetooth 5.2 ready with 3.5mm AUX and RCA inputs, Iconic vintage textured vinyl and brass control knobs.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      amplifiers: "1x 50W Class D (Woofer) + 2x 15W Class D (Tweeters)",
      frequency_response: "45 Hz - 20,000 Hz",
      max_spl: "97 dB @ 1 m",
      connectivity: ["Bluetooth 5.2", "3.5 mm Aux", "RCA"],
      controls: ["Volume", "Bass", "Treble", "Source Selector", "Brass Power Switch"],
      dimensions: "350 x 203 x 188 mm",
      weight: "4.25 kg"
    }),
    productModel: 'STANMORE-III-BLK',
    ficheTechnique: "Fiche Technique:\n- Puissance Audio : 80 Watts RMS (Amplificateurs de classe D dédiés)\n- Scène Sonore Élargie : Tweeters inclinés vers l'extérieur pour une immersion acoustique totale\n- Connectivité Polyvalente : Bluetooth 5.2, Entrée Jack 3,5 mm et Entrée RCA pour platine vinyle\n- Design Rock'n'Roll : Revêtement en vinyle texturé, grille vintage et boutons de réglage en laiton\n- متحدث منزلي كلاسيكي فخم بصوت قوي ونقي.",
    stockQuantity: 60,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 250,
    viewsCount: 1890,
    stockAvailable: 48,
    stockReserved: 0,
    stockSold: 12,
    name: 'Marshall Stanmore III Bluetooth Home Speaker (Brass & Black)',
    description: '80W vintage rock home speaker with room-filling stereo sound and brass knobs.',
    price: 379.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      power: "80W RMS Class D",
      inputs: "Bluetooth 5.2, RCA, 3.5mm AUX",
      finish: "Textured Vinyl & Brass"
    })
  },
  {
    id: 18,
    category: 5,
    subCategory: 8,
    productName: 'Nintendo Switch OLED Model - The Legend of Zelda Edition',
    productCompany: 'Nintendo',
    productPrice: 359,
    productPriceBeforeDiscount: 399,
    productDescription: 'Vibrant 7.0-inch OLED screen with deep contrast and vivid colors, Wide adjustable stand, 64GB internal storage, Enhanced audio speakers, Exclusive golden Zelda Tears of the Kingdom artwork.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      display: "7.0 OLED Multi-Touch (1280 x 720)",
      storage: "64GB (expandable via MicroSD up to 2TB)",
      battery: "4.5 to 9.0 hours (Lithium-ion 4310mAh)",
      dock: "White/Gold Dock with LAN Port and Hylian Crest",
      joycons: "Zelda Green & Gold Edition Joy-Con Controllers",
      weight: "420g with Joy-Cons"
    }),
    productModel: 'NSW-OLED-ZELDA-TOTK',
    ficheTechnique: "Fiche Technique:\n- Écran : 7,0 pouces OLED avec couleurs éclatantes et noirs profonds\n- Design Collecteur : Finitions dorées et symboles Hyliens inspirés de Zelda Tears of the Kingdom\n- Station d'accueil : Port Ethernet LAN filaire intégré pour des parties en ligne ultra-stables\n- Stockage : 64 Go de mémoire interne extensible par carte MicroSD\n- متعة الألعاب المنزلية والمحمولة مع إصدار زيلدا الحصري.",
    stockQuantity: 65,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 260,
    viewsCount: 2750,
    stockAvailable: 49,
    stockReserved: 0,
    stockSold: 16,
    name: 'Nintendo Switch OLED Model - The Legend of Zelda Edition',
    description: 'Collector OLED edition console with 7.0-inch screen and Zelda artwork.',
    price: 359.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      display: "7.0 OLED",
      edition: "Zelda Tears of the Kingdom",
      storage: "64GB + LAN Dock"
    })
  },
  {
    id: 19,
    category: 6,
    subCategory: 9,
    productName: 'LG UltraGear 45" Curved OLED 240Hz Gaming Monitor (45GS96QB)',
    productCompany: 'LG',
    productPrice: 1699,
    productPriceBeforeDiscount: 1899,
    productDescription: '45" WQHD (3440 x 1440) Curved OLED (800R), Blistering 240Hz Refresh Rate, 0.03ms (GtG) Response Time, VESA DisplayHDR True Black 400, USB-C 65W Power Delivery, Built-in Speakers with DTS Headphone:X.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      panel: "44.5 WQHD Curved OLED (800R curvature)",
      resolution: "3440 x 1440 at 240Hz",
      response_time: "0.03 ms (GtG)",
      contrast: "1,500,000:1 True Black",
      gamut: "DCI-P3 98.5%",
      ports: ["USB-C 65W PD", "2x HDMI 2.1", "DisplayPort 1.4", "2x USB 3.0 Downstream"],
      sync: ["NVIDIA G-SYNC Compatible", "AMD FreeSync Premium Pro"]
    }),
    productModel: '45GS96QB-OLED-240',
    ficheTechnique: "Fiche Technique:\n- Dalle Incurvée : 45 pouces OLED ultra-large avec courbure agressive 800R pour une immersion totale\n- Fréquence de Rafraîchissement : 240 Hz ultra-fluide avec temps de réponse instantané de 0,03 ms\n- Qualité d'image : VESA DisplayHDR True Black 400 avec 98,5% DCI-P3\n- Connectique : USB-C 65W Power Delivery avec haut-parleurs intégrés 7W x 2 DTS:X\n- شاشة الألعاب المنحنية الأضخم والأقوى للاعبين المحترفين وصناع المحتوى.",
    stockQuantity: 25,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 1320,
    viewsCount: 1150,
    stockAvailable: 18,
    stockReserved: 0,
    stockSold: 7,
    name: 'LG UltraGear 45" Curved OLED 240Hz Gaming Monitor (45GS96QB)',
    description: '45-inch 240Hz 0.03ms WQHD Curved 800R OLED gaming monitor with USB-C.',
    price: 1699.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      panel: "45 Curved OLED 800R",
      refresh_rate: "240Hz / 0.03ms",
      resolution: "3440 x 1440 WQHD",
      ports: "USB-C 65W PD + HDMI 2.1"
    })
  },
  {
    id: 20,
    category: 6,
    subCategory: 10,
    productName: 'Secretlab TITAN Evo 2026 Gaming Chair (SoftWeave Plus)',
    productCompany: 'Secretlab',
    productPrice: 549,
    productPriceBeforeDiscount: 629,
    productDescription: 'Award-winning ergonomic gaming chair. SoftWeave Plus high-breathability fabric (Cookies & Cream), 4-Way L-ADAPT Lumbar Support System, Magnetic Memory Foam Head Pillow with Cooling Gel, 4D Full-Metal Armrests.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      upholstery: "Secretlab SoftWeave Plus Fabric (High Durability & Breathability)",
      lumbar: "4-Way L-ADAPT Dynamic Lumbar Support",
      pillow: "Magnetic Memory Foam Head Pillow with Cooling Gel Layer",
      armrests: "CloudSwap Full-Metal 4D Armrests with Magnetic Replacement Caps",
      recline: "165-Degree Full Multi-Tilt Mechanism with Class 4 Hydraulics"
    }),
    productModel: 'TITAN-EVO-REG-SW',
    ficheTechnique: "Fiche Technique:\n- Revêtement : Tissu SoftWeave Plus doux, respirant et ultra-résistant à l'usure\n- Ergonomie : Système de soutien lombaire L-ADAPT réglable en 4 directions (hauteur et courbure)\n- Oreiller de tête : Mousse à mémoire de forme magnétique avec gel rafraîchissant sans sangles\n- Accoudoirs 4D entièrement métalliques avec système de changement rapide CloudSwap\n- كرسي ألعاب مريح ومثالي لجلسات اللعب والعمل الطويلة.",
    stockQuantity: 50,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 370,
    viewsCount: 1920,
    stockAvailable: 39,
    stockReserved: 0,
    stockSold: 11,
    name: 'Secretlab TITAN Evo 2026 Gaming Chair (SoftWeave Plus)',
    description: 'Ergonomic gaming chair with SoftWeave Plus fabric and magnetic cooling pillow.',
    price: 549.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      fabric: "SoftWeave Plus Breathable",
      lumbar: "4-Way L-ADAPT",
      pillow: "Magnetic Memory Foam Gel",
      armrests: "4D Full Metal"
    })
  },
  {
    id: 21,
    category: 6,
    subCategory: 10,
    productName: 'Dyson V15 Detect Absolute Cordless Smart Vacuum Cleaner',
    productCompany: 'Dyson',
    productPrice: 749,
    productPriceBeforeDiscount: 849,
    productDescription: '240 Air Watts of suction power, Laser Slim Fluffy optic cleaner head reveals invisible dust on hard floors, Piezo acoustic sensor counts and sizes particles on LCD screen, Up to 60 minutes run time.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      suction_power: "240 Air Watts (Dyson Hyperdymium Motor 125,000 RPM)",
      filtration: "Whole-Machine HEPA Filtration capturing 99.99% of microscopic particles down to 0.1 microns",
      sensor: "Acoustic Piezo Sensor Particle Counter",
      runtime: "Up to 60 Minutes Fade-Free Power",
      heads: ["Digital Motorbar Cleaner Head with De-Tangling Vanes", "Laser Slim Fluffy Optic Hard Floor Head"],
      weight: "3.0 kg"
    }),
    productModel: 'DYSON-V15-ABS-YEL',
    ficheTechnique: "Fiche Technique:\n- Puissance d'aspiration : 240 AW propulsée par le moteur Dyson Hyperdymium à 125 000 tr/min\n- Tête Optique Laser : Révèle la poussière invisible à l'œil nu sur les sols durs\n- Capteur Piézo : Mesure et compte en continu la taille des particules de poussière affichées sur écran LCD\n- Filtration HEPA : Capture 99,99% des particules microscopiques jusqu'à 0,1 micron\n- مكنسة ذكية لاسلكية متطورة لتنظيف عميق وفاخر للمنازل العصرية.",
    stockQuantity: 40,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 510,
    viewsCount: 1420,
    stockAvailable: 32,
    stockReserved: 0,
    stockSold: 8,
    name: 'Dyson V15 Detect Absolute Cordless Smart Vacuum Cleaner',
    description: 'Cordless vacuum with laser dust detection and real-time particle counting LCD.',
    price: 749.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      power: "240 Air Watts",
      laser: "Laser Slim Fluffy Optic",
      filtration: "99.99% HEPA",
      runtime: "60 Mins"
    })
  },
  {
    id: 22,
    category: 3,
    subCategory: 13,
    productName: 'Sonos Arc Premium Smart Soundbar with Dolby Atmos (Matte Black)',
    productCompany: 'Sonos',
    productPrice: 899,
    productPriceBeforeDiscount: 999,
    productDescription: '11 high-performance internal drivers including 2 dedicated up-firing height channels, Dolby Atmos 3D acoustic soundstage, Apple AirPlay 2, HDMI eARC, Speech Enhancement for crystal-clear dialogue, Trueplay acoustic tuning.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      amplifiers: "11 Class-D Digital Amplifiers matched to acoustic architecture",
      drivers: ["8 Elliptical Woofers", "3 Silk-Dome Tweeters", "2 Dedicated Up-Firing Height Channels"],
      audio_formats: ["Dolby Atmos", "Dolby Digital Plus", "Dolby TrueHD", "PCM Multichannel"],
      connectivity: ["HDMI eARC", "Optical Audio Adapter included", "Apple AirPlay 2", "Wi-Fi"],
      tuning: "Trueplay Room Acoustic Tuning"
    }),
    productModel: 'SONOS-ARC-BLK',
    ficheTechnique: "Fiche Technique:\n- Immersion Cinéma : 11 haut-parleurs haute précision avec 2 canaux orientés vers le haut pour Dolby Atmos 3D\n- Clarté des dialogues : Fonction Speech Enhancement qui isole les voix pour ne manquer aucun mot\n- Calibrage Trueplay : Ajuste la signature acoustique en fonction de l'agencement de votre salon\n- Connectivité : HDMI eARC avec prise en charge complète d'Apple AirPlay 2 et Spotify Connect\n- ساوند بار سينمائي فاخر بتجربة صوتية ثلاثية الأبعاد Dolby Atmos.",
    stockQuantity: 35,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 670,
    viewsCount: 1120,
    stockAvailable: 27,
    stockReserved: 0,
    stockSold: 8,
    name: 'Sonos Arc Premium Smart Soundbar with Dolby Atmos (Matte Black)',
    description: 'Cinematic smart soundbar with 11 drivers, Dolby Atmos 3D, and HDMI eARC.',
    price: 899.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      drivers: "11 Amplified Drivers",
      audio: "Dolby Atmos 3D Height Channels",
      connectivity: "HDMI eARC + AirPlay 2"
    })
  },
  {
    id: 23,
    category: 4,
    subCategory: 7,
    productName: 'Garmin Fenix 8 Solar Multisport GPS Smartwatch (51mm Titanium)',
    productCompany: 'Garmin',
    productPrice: 1099,
    productPriceBeforeDiscount: 1199,
    productDescription: 'Power Sapphire Solar charging lens providing up to 48 days of battery life, Grade 5 Titanium bezel with DLC coating, Built-in Speaker and Mic for voice calls, TopoActive multi-continent color maps, Bright LED flashlight.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      lens: "Power Sapphire Solar Charging Crystal",
      bezel: "Titanium with Diamond-Like Carbon (DLC) Coating",
      display: "1.4 Sunlight-Visible Transflective MIP (280 x 280)",
      battery: ["Up to 48 Days (Smartwatch with Solar)", "Up to 149 Hours (GPS with Solar)"],
      sensors: ["Multi-Band GNSS with SatIQ", "Elevate Gen 5 Heart Rate & ECG", "Barometric Altimeter", "Pulse Ox"],
      features: ["Integrated LED Flashlight", "Offline TopoActive Maps", "40m Dive Rating with Leakproof Buttons"]
    }),
    productModel: 'FENIX8-51-SOL-TIT',
    ficheTechnique: "Fiche Technique:\n- Verre Solaire Power Sapphire : Recharge solaire offrant jusqu'à 48 jours d'autonomie en mode montre connectée\n- Boîtier & Lunette : Titane Grade 5 avec revêtement DLC haute résistance aux chocs et rayures\n- Cartographie : Cartes TopoActive mondiales préchargées avec guidage GPS multi-bandes ultra-précis SatIQ\n- Étanchéité & Plongée : Étanche jusqu'à 40 mètres avec boutons étanches inductifs\n- Lampe torche LED intégrée à intensité variable avec faisceau blanc et rouge.",
    stockQuantity: 30,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 820,
    viewsCount: 1750,
    stockAvailable: 24,
    stockReserved: 0,
    stockSold: 6,
    name: 'Garmin Fenix 8 Solar Multisport GPS Smartwatch (51mm Titanium)',
    description: 'Expedition GPS smartwatch with solar sapphire lens, titanium bezel, and 48-day battery.',
    price: 1099.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      lens: "Power Sapphire Solar",
      bezel: "51mm Titanium DLC",
      battery: "Up to 48 Days",
      maps: "TopoActive Offline Global"
    })
  },
  {
    id: 24,
    category: 5,
    subCategory: 14,
    productName: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard (Gateron Red)',
    productCompany: 'Keychron',
    productPrice: 219,
    productPriceBeforeDiscount: 249,
    productDescription: '75% layout premium custom mechanical keyboard. Full CNC 6063 Aluminum body, Double-Gasket acoustic mount, Hot-Swappable RGB PCB, QMK/VIA key remapping, Bluetooth 5.1 and Type-C wired, Gateron Jupiter Red linear switches.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      layout: "75% Compact (81 Keys + Programmable Rotary Knob)",
      chassis: "Full 6063 Solid CNC Aluminum Anodized Chassis",
      structure: "Double Gasket Acoustic Mount with Sound Absorbing Foam",
      switches: "Pre-Lubed Gateron Jupiter Red Linear (Hot-Swappable 3/5-pin)",
      connectivity: ["Bluetooth 5.1 (3 Devices)", "Type-C Wired 1000Hz Polling Rate"],
      keycaps: "KSA Profile Double-Shot PBT Keycaps"
    }),
    productModel: 'KEYCHRON-Q1PRO-RED',
    ficheTechnique: "Fiche Technique:\n- Châssis : Aluminium massif 6063 usiné par CNC avec finition anodisée haut de gamme\n- Structure Double Gasket : Amortissement acoustique double couche pour une frappe douce et un son feutré (\"Thock\")\n- Switches Hot-Swap : Gateron Jupiter Red linéaires lubrifiés d'usine remplaçables sans soudure\n- Personnalisation : Entièrement programmable avec les logiciels open-source QMK et VIA\n- Molette rotative programmable en aluminium pour le volume et la luminosité.",
    stockQuantity: 75,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 140,
    viewsCount: 2600,
    stockAvailable: 61,
    stockReserved: 0,
    stockSold: 14,
    name: 'Keychron Q1 Pro Wireless Custom Mechanical Keyboard (Gateron Red)',
    description: 'Full CNC aluminum 75% mechanical keyboard with hot-swappable switches and QMK/VIA.',
    price: 219.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      chassis: "Full 6063 CNC Aluminum",
      structure: "Double Gasket Mount",
      switches: "Hot-Swap Gateron Jupiter Red",
      software: "QMK / VIA Programmable"
    })
  },
  {
    id: 25,
    category: 6,
    subCategory: 15,
    productName: 'GoPro HERO 13 Black Creator Edition (5.3K60 Video + Volta Grip)',
    productCompany: 'GoPro',
    productPrice: 599,
    productPriceBeforeDiscount: 699,
    productDescription: '5.3K 60fps / 4K 120fps video, HyperSmooth 6.0 Video Stabilization with 360° Horizon Lock, Volta Battery Grip with over 5 hours of continuous 4K recording, Media Mod directional microphone, Light Mod LED.',
    productImage1: 'img_main.jpg',
    productImage2: 'img_angle.jpg',
    productImage3: 'img_detail.jpg',
    shippingCharge: 0,
    productAvailability: 'In Stock',
    specifications: JSON.stringify({
      video: ["5.3K 60fps", "4K 120fps", "2.7K 240fps (8x Slo-Mo)", "10-Bit GP-Log & HLG HDR"],
      stabilization: "HyperSmooth 6.0 with AutoBoost and 360 Horizon Lock",
      sensor: "1/1.9 CMOS 27MP Stills in 8:7 Full Sensor Mode",
      accessories: ["Volta Motorized Battery Grip (4900mAh)", "Media Mod Directional Mic", "Light Mod 200 Lumen Waterproof LED"],
      waterproof: "Camera Body 10m (33ft) without housing"
    }),
    productModel: 'GOPRO-HERO13-CREATOR',
    ficheTechnique: "Fiche Technique:\n- Résolution Vidéo : 5,3K à 60 ips / 4K à 120 ips avec profil 10 bits GP-Log et HLG HDR\n- Stabilisation : HyperSmooth 6.0 avec verrouillage de l'horizon à 360° pour des vidéos d'une fluidité absolue\n- Pack Creator Edition : Poignée batterie Volta (plus de 5 heures d'enregistrement 4K), Module Médias avec micro directionnel et Torche LED 200 lumens\n- Robustesse : Étanche jusqu'à 10 mètres sans caisson additionnel\n- كاميرا الأكشن والتصوير الاحترافي الأكثر شهرة مع جميع ملحقات صناع المحتوى.",
    stockQuantity: 50,
    warehouseLocation: 'Casablanca Central Hub-A1',
    costPrice: 410,
    viewsCount: 3100,
    stockAvailable: 39,
    stockReserved: 0,
    stockSold: 11,
    name: 'GoPro HERO 13 Black Creator Edition (5.3K60 Video + Volta Grip)',
    description: 'All-in-one 5.3K60 content creation action camera with Volta grip and directional mic.',
    price: 599.00,
    currency: 'USD',
    fiche_technique: JSON.stringify({
      video: "5.3K 60fps / 4K 120fps",
      stabilization: "HyperSmooth 6.0 360 Horizon",
      pack: "Volta Grip + Media Mod + LED Light"
    })
  }
];

function escapeSql(str) {
  if (str === null || str === undefined) return 'NULL';
  return "'" + String(str).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

async function seedAllProducts() {
  console.log(`🚀 Generating complete SQL seed script for ${products.length} Extended Flagship Products...`);

  let sql = `USE shopping;\n\n`;
  sql += `SET FOREIGN_KEY_CHECKS = 0;\n\n`;
  sql += `DELETE FROM products WHERE id > 0;\n`;
  sql += `DELETE FROM inventory WHERE product_id > 0;\n\n`;

  sql += `INSERT INTO subcategory (id, categoryid, subcategory, creationDate) VALUES\n`;
  sql += `(11, 1, 'Gaming Laptops & Workstations', NOW()),\n`;
  sql += `(12, 2, 'Creative Pro Tablets', NOW()),\n`;
  sql += `(13, 3, 'Smart Speakers & Home Theater', NOW()),\n`;
  sql += `(14, 5, 'Gaming Keyboards & Custom Gear', NOW()),\n`;
  sql += `(15, 6, 'Cameras & Cinema Drones', NOW())\n`;
  sql += `ON DUPLICATE KEY UPDATE subcategory = VALUES(subcategory);\n\n`;

  for (const p of products) {
    sql += `INSERT INTO products (\n`;
    sql += `  id, category, subCategory, productName, productCompany, productPrice, productPriceBeforeDiscount,\n`;
    sql += `  productDescription, productImage1, productImage2, productImage3, shippingCharge, productAvailability,\n`;
    sql += `  specifications, productModel, ficheTechnique, stockQuantity, warehouseLocation, costPrice, viewsCount,\n`;
    sql += `  stockAvailable, stockReserved, stockSold, name, description, price, currency, fiche_technique\n`;
    sql += `) VALUES (\n`;
    sql += `  ${p.id}, ${p.category}, ${p.subCategory}, ${escapeSql(p.productName)}, ${escapeSql(p.productCompany)},\n`;
    sql += `  ${p.productPrice}, ${p.productPriceBeforeDiscount}, ${escapeSql(p.productDescription)},\n`;
    sql += `  ${escapeSql(p.productImage1)}, ${escapeSql(p.productImage2)}, ${escapeSql(p.productImage3)},\n`;
    sql += `  ${p.shippingCharge}, ${escapeSql(p.productAvailability)}, ${escapeSql(p.specifications)},\n`;
    sql += `  ${escapeSql(p.productModel)}, ${escapeSql(p.ficheTechnique)}, ${p.stockQuantity},\n`;
    sql += `  ${escapeSql(p.warehouseLocation)}, ${p.costPrice}, ${p.viewsCount}, ${p.stockAvailable},\n`;
    sql += `  ${p.stockReserved}, ${p.stockSold}, ${escapeSql(p.name)}, ${escapeSql(p.description)},\n`;
    sql += `  ${p.price}, ${escapeSql(p.currency)}, ${escapeSql(p.fiche_technique)}\n`;
    sql += `);\n\n`;

    sql += `INSERT INTO inventory (product_id, available_qty, reserved_qty, sold_qty)\n`;
    sql += `VALUES (${p.id}, ${p.stockAvailable}, ${p.stockReserved}, ${p.stockSold});\n\n`;
  }

  sql += `SET FOREIGN_KEY_CHECKS = 1;\n`;

  const scriptPath = path.join(__dirname, 'temp_seed_25_products.sql');
  fs.writeFileSync(scriptPath, sql, { encoding: 'utf8' });
  console.log(`  ✓ Written SQL seed script to: ${scriptPath}`);

  console.log(`  Executing in MariaDB container (shopping_db)...`);
  execSync(`Get-Content -Encoding UTF8 "${scriptPath}" | docker exec -i shopping_db mariadb -u shopping_user -pshopping_pass shopping`, { shell: 'powershell.exe' });

  console.log(`\n✅ All ${products.length} Extended Flagship Products seeded successfully!`);
}

seedAllProducts();
